
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class Client extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form Client
	 */
	Socket connection;
	String host;
	ObjectInputStream input;
	ObjectOutputStream output;
	Move move=new Move();

	public Client(String host) {
		super("Client");
		//this.host=host;
		this.host=host;
		System.out.println(host);
		initComponents();


	}
	public void deactivate(){
		if(move.getPlayer1Left()==0){
			jButton4.setEnabled(false);
			jButton9.setEnabled(false);
			jButton11.setEnabled(false);
			jButton1.setEnabled(false);
			jButton2.setEnabled(false);
			jButton3.setEnabled(false);          
		}
		if(move.getPlayer1Right()==0){
			jButton1.setEnabled(false);
			jButton8.setEnabled(false);
			jButton12.setEnabled(false);
			jButton4.setEnabled(false);
			jButton5.setEnabled(false);
			jButton6.setEnabled(false);
		}
		if(move.getPlayer2Left()==0){
			jButton3.setEnabled(false);
			jButton5.setEnabled(false);
			jButton10.setEnabled(false);
			jButton7.setEnabled(false);
			jButton8.setEnabled(false);
			jButton9.setEnabled(false);
		}
		if(move.getPlayer2Right()==0){
			jButton2.setEnabled(false);
			jButton6.setEnabled(false);
			jButton7.setEnabled(false);
			jButton10.setEnabled(false);
			jButton11.setEnabled(false);
			jButton12.setEnabled(false);
		}
		if(move.getPlayer1Left()+move.getPlayer1Right()%2!=0){
			jButton17.setEnabled(false);
		}
		if(move.getPlayer2Left()+move.getPlayer2Right()%2!=0){
			jButton18.setEnabled(false);
		}


	}
	public void deactivatePlayer1(){
		jButton1.setEnabled(false);
		jButton2.setEnabled(false);
		jButton3.setEnabled(false);
		jButton4.setEnabled(false);
		jButton5.setEnabled(false);
		jButton6.setEnabled(false);
		jButton17.setEnabled(false);

	}

	public void activatePlayer2(){
		jButton7.setEnabled(true);
		jButton8.setEnabled(true);
		jButton9.setEnabled(true);
		jButton10.setEnabled(true);
		jButton11.setEnabled(true);
		jButton12.setEnabled(true);
		jButton18.setEnabled(true);

	}
	public void deactivatePlayer2(){

		jButton7.setEnabled(false);
		jButton8.setEnabled(false);
		jButton9.setEnabled(false);
		jButton10.setEnabled(false);
		jButton11.setEnabled(false);
		jButton12.setEnabled(false);
		jButton18.setEnabled(false);

	}
	public void activatePlayer1(){
		jButton1.setEnabled(true);
		jButton2.setEnabled(true);
		jButton3.setEnabled(true);
		jButton4.setEnabled(true);
		jButton5.setEnabled(true);
		jButton6.setEnabled(true);
		jButton17.setEnabled(true);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	 // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	 private void initComponents() {

		 jPanel1 = new javax.swing.JPanel();
		 jTextField1 = new javax.swing.JTextField();
		 jButton1 = new javax.swing.JButton();
		 jButton2 = new javax.swing.JButton();
		 jButton3 = new javax.swing.JButton();
		 jPanel2 = new javax.swing.JPanel();
		 jTextField2 = new javax.swing.JTextField();
		 jButton4 = new javax.swing.JButton();
		 jButton5 = new javax.swing.JButton();
		 jButton6 = new javax.swing.JButton();
		 jPanel3 = new javax.swing.JPanel();
		 jButton7 = new javax.swing.JButton();
		 jButton8 = new javax.swing.JButton();
		 jButton9 = new javax.swing.JButton();
		 jTextField3 = new javax.swing.JTextField();
		 jPanel4 = new javax.swing.JPanel();
		 jButton10 = new javax.swing.JButton();
		 jButton11 = new javax.swing.JButton();
		 jButton12 = new javax.swing.JButton();
		 jTextField4 = new javax.swing.JTextField();
		 jLabel1 = new javax.swing.JLabel();
		 jLabel2 = new javax.swing.JLabel();
		 jSeparator1 = new javax.swing.JSeparator();
		 jButton17 = new javax.swing.JButton();
		 jButton18 = new javax.swing.JButton();

		 jTextField1.setName("jTextField1");
		 jTextField2.setName("jTextField2");
		 jTextField3.setName("jTextField3");
		 jTextField4.setName("jTextField4");
		 setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		 addWindowListener(new java.awt.event.WindowAdapter() {
			 public void windowOpened(java.awt.event.WindowEvent evt) {
				 formWindowOpened(evt);
			 }
		 });

		 jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		 jTextField1.setColumns(45);
		 jTextField1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
		 jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		 jTextField1.setText("1");


		 jButton1.setText("Side");
		 jButton1.setEnabled(false);


		 jButton2.setText("Diagonal");
		 jButton2.setEnabled(false);
		 ;

		 jButton3.setText("Forward");
		 jButton3.setEnabled(false);


		 javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		 jPanel1.setLayout(jPanel1Layout);
		 jPanel1Layout.setHorizontalGroup(
				 jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				 .addGroup(jPanel1Layout.createSequentialGroup()
						 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								 .addGroup(jPanel1Layout.createSequentialGroup()
										 .addContainerGap()
										 .addComponent(jButton3)
										 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
												 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												 .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
												 .addGap(30, 30, 30)))
												 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														 .addComponent(jButton2)
														 .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
														 .addGap(21, 21, 21))
				 );
		 jPanel1Layout.setVerticalGroup(
				 jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				 .addGroup(jPanel1Layout.createSequentialGroup()
						 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								 .addGroup(jPanel1Layout.createSequentialGroup()
										 .addContainerGap()
										 .addComponent(jButton1))
										 .addGroup(jPanel1Layout.createSequentialGroup()
												 .addGap(20, 20, 20)
												 .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
												 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												 .addComponent(jButton2)
												 .addGap(5, 5, 5)
												 .addComponent(jButton3)
												 .addContainerGap())
				 );

		 jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		 jTextField2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
		 jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		 jTextField2.setText("1");


		 jButton4.setText("Side");
		 jButton4.setEnabled(false);


		 jButton5.setText("Diagonal");
		 jButton5.setEnabled(false);


		 jButton6.setText("Forward");
		 jButton6.setEnabled(false);


		 javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		 jPanel2.setLayout(jPanel2Layout);
		 jPanel2Layout.setHorizontalGroup(
				 jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				 .addGroup(jPanel2Layout.createSequentialGroup()
						 .addGap(19, 19, 19)
						 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								 .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
								 .addComponent(jButton5))
								 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										 .addComponent(jButton6)
										 .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
										 .addGap(22, 22, 22))
				 );
		 jPanel2Layout.setVerticalGroup(
				 jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				 .addGroup(jPanel2Layout.createSequentialGroup()
						 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								 .addGroup(jPanel2Layout.createSequentialGroup()
										 .addContainerGap()
										 .addComponent(jButton4))
										 .addGroup(jPanel2Layout.createSequentialGroup()
												 .addGap(20, 20, 20)
												 .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
												 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												 .addComponent(jButton5)
												 .addGap(5, 5, 5)
												 .addComponent(jButton6)
												 .addContainerGap())
				 );

		 jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		 jButton7.setText("Side");
		 jButton7.setEnabled(false);
		 jButton7.addActionListener(new java.awt.event.ActionListener() {
			 public void actionPerformed(java.awt.event.ActionEvent evt) {
				 jButton7ActionPerformed(evt);
			 }
		 });

		 jButton8.setText("Diagonal");
		 jButton8.setEnabled(false);
		 jButton8.addActionListener(new java.awt.event.ActionListener() {
			 public void actionPerformed(java.awt.event.ActionEvent evt) {
				 jButton8ActionPerformed(evt);
			 }
		 });


		 jButton9.setText("Forward");
		 jButton9.setEnabled(false);
		 jButton9.addActionListener(new java.awt.event.ActionListener() {
			 public void actionPerformed(java.awt.event.ActionEvent evt) {
				 jButton9ActionPerformed(evt);
			 }
		 });

		 jTextField3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
		 jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		 jTextField3.setText("1");


		 javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		 jPanel3.setLayout(jPanel3Layout);
		 jPanel3Layout.setHorizontalGroup(
				 jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
						 .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								 .addGroup(jPanel3Layout.createSequentialGroup()
										 .addContainerGap()
										 .addComponent(jButton9)
										 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
												 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												 .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
												 .addGap(32, 32, 32)))
												 .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														 .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING)
														 .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
														 .addGap(20, 20, 20))
				 );
		 jPanel3Layout.setVerticalGroup(
				 jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
						 .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								 .addGroup(jPanel3Layout.createSequentialGroup()
										 .addContainerGap()
										 .addComponent(jButton9)
										 .addGap(17, 17, 17)
										 .addComponent(jTextField3))
										 .addGroup(jPanel3Layout.createSequentialGroup()
												 .addGap(32, 32, 32)
												 .addComponent(jButton8)
												 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												 .addComponent(jButton7)))
												 .addGap(29, 29, 29))
				 );

		 jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		 jButton10.setText("Side");
		 jButton10.setEnabled(false);
		 jButton10.addActionListener(new java.awt.event.ActionListener() {
			 public void actionPerformed(java.awt.event.ActionEvent evt) {
				 jButton10ActionPerformed(evt);
			 }
		 });

		 jButton11.setText("Diagonal");
		 jButton11.setEnabled(false);
		 jButton11.addActionListener(new java.awt.event.ActionListener() {
			 public void actionPerformed(java.awt.event.ActionEvent evt) {
				 jButton11ActionPerformed(evt);
			 }
		 });

		 jButton12.setText("Forward");
		 jButton12.setEnabled(false);
		 jButton12.addActionListener(new java.awt.event.ActionListener() {
			 public void actionPerformed(java.awt.event.ActionEvent evt) {
				 jButton12ActionPerformed(evt);
			 }
		 });

		 jTextField4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
		 jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		 jTextField4.setText("1");


		 javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		 jPanel4.setLayout(jPanel4Layout);
		 jPanel4Layout.setHorizontalGroup(
				 jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
						 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								 .addGroup(jPanel4Layout.createSequentialGroup()
										 .addGap(19, 19, 19)
										 .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
										 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
												 .addContainerGap(16, Short.MAX_VALUE)
												 .addComponent(jButton11)
												 .addGap(18, 18, 18)))
												 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
														 .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														 .addComponent(jTextField4))
														 .addGap(33, 33, 33))
				 );
		 jPanel4Layout.setVerticalGroup(
				 jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
						 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								 .addGroup(jPanel4Layout.createSequentialGroup()
										 .addContainerGap()
										 .addComponent(jButton12))
										 .addGroup(jPanel4Layout.createSequentialGroup()
												 .addGap(32, 32, 32)
												 .addComponent(jButton11)))
												 .addGap(10, 10, 10)
												 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														 .addGroup(jPanel4Layout.createSequentialGroup()
																 .addGap(0, 0, Short.MAX_VALUE)
																 .addComponent(jButton10))
																 .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
																 .addGap(27, 27, 27))
				 );

		 jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		 jLabel1.setForeground(new java.awt.Color(255, 0, 0));
		 jLabel1.setText("Player 1");

		 jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		 jLabel2.setForeground(new java.awt.Color(51, 255, 51));
		 jLabel2.setText("Player 2");

		 jButton17.setText("<< Split >>");
		 jButton17.setEnabled(false);

		 jButton18.setText("<< Split >>");
		 jButton18.addActionListener(new java.awt.event.ActionListener() {
			 public void actionPerformed(java.awt.event.ActionEvent evt) {
				 jButton18ActionPerformed(evt);
			 }
		 });

		 javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		 getContentPane().setLayout(layout);
		 layout.setHorizontalGroup(
				 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				 .addGroup(layout.createSequentialGroup()
						 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								 .addGroup(layout.createSequentialGroup()
										 .addContainerGap()
										 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												 .addGroup(layout.createSequentialGroup()
														 .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														 .addGap(18, 18, 18)
														 .addComponent(jButton17))
														 .addGroup(layout.createSequentialGroup()
																 .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																 .addGap(18, 18, 18)
																 .addComponent(jButton18)))
																 .addGap(18, 18, Short.MAX_VALUE)
																 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																		 .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		 .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
																		 .addGroup(layout.createSequentialGroup()
																				 .addGap(241, 241, 241)
																				 .addComponent(jLabel2)
																				 .addGap(0, 0, Short.MAX_VALUE)))
																				 .addContainerGap())
																				 .addGroup(layout.createSequentialGroup()
																						 .addGap(44, 44, 44)
																						 .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
																						 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
																						 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																								 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																								 .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
																								 .addGap(229, 229, 229))
				 );
		 layout.setVerticalGroup(
				 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						 .addContainerGap()
						 .addComponent(jLabel1)
						 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								 .addGroup(layout.createSequentialGroup()
										 .addGap(18, 18, 18)
										 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												 .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												 .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
												 .addGroup(layout.createSequentialGroup()
														 .addGap(54, 54, 54)
														 .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
														 .addGap(23, 23, 23)
														 .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
														 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																 .addGroup(layout.createSequentialGroup()
																		 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																				 .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																				 .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
																				 .addGroup(layout.createSequentialGroup()
																						 .addGap(42, 42, 42)
																						 .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
																						 .addGap(18, 18, 18)
																						 .addComponent(jLabel2)
																						 .addContainerGap())
				 );

		 pack();
		 System.out.println("sdflkjfl");
	 }

	 public void startRunning(){
		 try {
			 connection=new Socket(host,3128);
			 System.out.println(host+" connect");
			 System.out.println("Connected with "+connection.getInetAddress().getHostName());
			 System.out.println("Setting Stream");
			 output=new ObjectOutputStream(connection.getOutputStream());
			 output.flush();
			 input=new ObjectInputStream(connection.getInputStream());
			 System.out.println("Stream Completed");
			 new Thread(new Runnable() {

				 @Override
				 public void run() {
					 whilePlaying();
				 }
			 }).start();
		 } catch (IOException e) {
			 e.printStackTrace();
		 }

	 }
	 public void send(){
		 try {
			 output.writeObject(move);
			 output.flush();
		 } catch (IOException e) {
			 // TODO Auto-generated catch block
			 e.printStackTrace();
		 }
	 }
	 public synchronized void whilePlaying(){
		 while(move.isGameOver()==false){
			 try {
				 move=(Move)input.readObject();
				 activatePlayer2();
				 deactivate();
			 } catch (ClassNotFoundException e) {

				 e.printStackTrace();
			 } catch (IOException e) {

				 e.printStackTrace();
			 }
			 showScreen();
		 }
	 }
	 public int getLastHandValue(JTextField hand){
		 int lastHandValue=0;
		 if(hand.getName().equals("jTextField1"))
		 {lastHandValue=move.getPlayer1Left();System.out.println("Text1");}
		 else if(hand.getName().equals("jTextField2"))
		 {lastHandValue=move.getPlayer1Right();System.out.println("Text2");}
		 else if(hand.getName().equals("jTextField3"))
		 {lastHandValue=move.getPlayer2Left();System.out.println("Text3");}
		 else if(hand.getName().equals("jTextField4"))
		 {lastHandValue=move.getPlayer2Right();System.out.println("Text4");}

		 return lastHandValue;

	 }

	 public void showScreen(){
		 new Thread(new Runnable(){

		
			@Override
			 public void run() {
				
				int player1left = Integer.parseInt(jTextField1.getText());
				int player1right = Integer.parseInt(jTextField2.getText());
				int player2left = Integer.parseInt(jTextField3.getText());
				int player2right = Integer.parseInt(jTextField4.getText());
		
				 //player1 left
				 for(int i=player1left;(i%5)!=(move.getPlayer1Left()+1)%5;i++){
					 jTextField1.setText(""+i%5);
					 try {
		    				Thread.sleep(1000);
		    			} catch (InterruptedException e) {

						e.printStackTrace();
		    			}		    			
				 }
				 
				 //player1 right
				 for(int i=player1right;(i%5)!=(move.getPlayer1Right()+1)%5;i++){
					 jTextField2.setText(""+i%5);
					 try {
		    				Thread.sleep(1000);
		    			} catch (InterruptedException e) {

						e.printStackTrace();
		    			}		    			
				 }
				 //player2 left
				 for(int i=player2left;(i%5)!=(move.getPlayer2Left()+1)%5;i++){
					 jTextField3.setText(""+i%5);
					 try {
		    				Thread.sleep(1000);
		    			} catch (InterruptedException e) {

						e.printStackTrace();
		    			}		    			
				 }
				 //player1 left
				 for(int i=player2right;(i%5)!=(move.getPlayer2Right()+1)%5;i++){
					 jTextField4.setText(""+i%5);
					 try {
		    				Thread.sleep(1000);
		    			} catch (InterruptedException e) {

						e.printStackTrace();
		    			}		    			
				 }
				 

				 
				 /*JTextField curHand= move.getLastMoveOn();
				 System.out.println("curHand="+curHand.getName());
				 if(move.getLastMoveOn()==null)
		    	{
		    		jTextField1.setText(""+move.getPlayer1Left());
		    		jTextField2.setText(""+move.getPlayer1Right());
		    		jTextField3.setText(""+move.getPlayer2Left());
		    		jTextField4.setText(""+move.getPlayer2Right());
		    		System.out.println("Hand is null");

		    	}
		    	else{
		    		int lastHandValue=getLastHandValue(curHand);
		    		System.out.println(lastHandValue);
		    		int assertVal = lastHandValue;
		    		for(int i=Integer.parseInt(curHand.getText());(i%5)!=(lastHandValue+1)%5;i++)
		    		{
		    			
		    			assert(lastHandValue==assertVal):"lasthand value changed!!!!";
		    			final int another = i; 
		    			
		    			System.out.println("i="+i%5);
		    			try {
		    				Thread.sleep(1000);
		    			} catch (InterruptedException e) {

						e.printStackTrace();
		    			}
		    			
		    			
		    			SwingUtilities.invokeLater(new Runnable() {
							
							@Override
							public void run() {
								// TODO Auto-generated method stub
								curHand.setText(""+(another%5));
				    			repaint();
				    					
							}
						});

		    			//repaint();
		    		}
		    	}
		    	
		    	*/
		    	/*
				 jTextField1.setText(""+move.getPlayer1Left());
				 jTextField2.setText(""+move.getPlayer1Right());
				 jTextField3.setText(""+move.getPlayer2Left());
				 jTextField4.setText(""+move.getPlayer2Right());
				*/
			 }	
		 }).start();
	 }

	 public void checkWin(){
		 if(move.getPlayer1Left()==0&&move.getPlayer1Right()==0)
		 {
			 JOptionPane.showMessageDialog(null,"Player 2 Wins");
			 move.setGameOver(true);
		 }
	 }
	 private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		 move.setPlayer2Right((move.getPlayer2Left()+move.getPlayer2Right())%5);
		 move.setLastMoveOn(jTextField4);
		 showScreen();
		 deactivatePlayer2();
		 checkWin();  
		 send();
	 }                                        

	 private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		 move.setPlayer1Right((move.getPlayer2Left()+move.getPlayer1Right())%5);
		 move.setLastMoveOn(jTextField2);
		 showScreen();
		 deactivatePlayer2();
		 checkWin();  
		 send(); 
	 }                                        

	 private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		 move.setPlayer1Left((move.getPlayer2Left()+move.getPlayer1Left())%5);
		 move.setLastMoveOn(jTextField1);
		 showScreen();
		 deactivatePlayer2();
		 checkWin();  
		 send();
	 }                                        

	 private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		 move.setPlayer2Left((move.getPlayer2Left()+move.getPlayer2Right())%5);
		 move.setLastMoveOn(jTextField3);
		 showScreen();
		 deactivatePlayer2();
		 checkWin();  
		 send();
	 }                                        

	 private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		 move.setPlayer1Left((move.getPlayer2Right()+move.getPlayer1Left())%5);
		 move.setLastMoveOn(jTextField1);
		 showScreen();
		 deactivatePlayer2();
		 checkWin();  
		 send();
	 }                                        

	 private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		 move.setPlayer1Right((move.getPlayer1Right()+move.getPlayer2Right())%5);
		 move.setLastMoveOn(jTextField2);
		 showScreen();
		 deactivatePlayer2();
		 checkWin();  
		 send();
	 }                                        


	 private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {                                          
		 move.setLastMoveOn(null);
		 int player2Left=move.getPlayer2Left();
		 int player2Right=move.getPlayer2Right();
		 int total=player2Left+player2Right;
		 move.setPlayer2Left(total/2);
		 move.setPlayer2Right(total-(total/2));
		 showScreen();
		 deactivatePlayer2();
		 checkWin();  
		 send();
	 }

	 private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  

		 jButton7.setEnabled(true);
		 jButton8.setEnabled(true);
		 jButton9.setEnabled(true);
		 jButton10.setEnabled(true);
		 jButton11.setEnabled(true);
		 jButton12.setEnabled(true);
		 jButton18.setEnabled(true);
		 jTextField1.setEditable(false);
		 jTextField2.setEditable(false);
		 jTextField3.setEditable(false);
		 jTextField4.setEditable(false);


	 }                                 

	 /**
	  * @param args the command line arguments
	  */
	  public static void main(String args[]) {
		 System.out.println("In main");
		 /* Set the Nimbus look and feel */
		 //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		 /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		  * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		  */
		 try {
			 for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				 if ("Nimbus".equals(info.getName())) {
					 javax.swing.UIManager.setLookAndFeel(info.getClassName());
					 break;
				 }
			 }
		 } catch (ClassNotFoundException ex) {
			 java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		 } catch (InstantiationException ex) {
			 java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		 } catch (IllegalAccessException ex) {
			 java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		 } catch (javax.swing.UnsupportedLookAndFeelException ex) {
			 java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		 }
		 //</editor-fold>


		 //Client client= new Client();

		 System.out.println(" jhb ");
		 // client.setVisible(true);
		 //client.startRunning();

	  }

	  // Variables declaration - do not modify                     
	  private javax.swing.JButton jButton1;
	  private javax.swing.JButton jButton10;
	  private javax.swing.JButton jButton11;
	  private javax.swing.JButton jButton12;
	  private javax.swing.JButton jButton17;
	  private javax.swing.JButton jButton18;
	  private javax.swing.JButton jButton2;
	  private javax.swing.JButton jButton3;
	  private javax.swing.JButton jButton4;
	  private javax.swing.JButton jButton5;
	  private javax.swing.JButton jButton6;
	  private javax.swing.JButton jButton7;
	  private javax.swing.JButton jButton8;
	  private javax.swing.JButton jButton9;
	  private javax.swing.JLabel jLabel1;
	  private javax.swing.JLabel jLabel2;
	  private javax.swing.JPanel jPanel1;
	  private javax.swing.JPanel jPanel2;
	  private javax.swing.JPanel jPanel3;
	  private javax.swing.JPanel jPanel4;
	  private javax.swing.JSeparator jSeparator1;
	  private javax.swing.JTextField jTextField1;
	  private javax.swing.JTextField jTextField2;
	  private javax.swing.JTextField jTextField3;
	  private javax.swing.JTextField jTextField4;

	  // End of variables declaration                   
}
